# analysis_options.yaml

include: package:flutter_lints/flutter.yaml


analyzer:
  exclude:
    - "**/kanban/**/*.dart"
    

linter:
  
  rules:
    - camel_case_types
    - constant_identifier_names
    - prefer_const_constructors
    - sort_constructors_first
    - avoid_unnecessary_containers
    - prefer_final_fields
    - avoid_returning_null_for_void
    - avoid_empty_else
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - avoid_init_to_null
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - prefer_asserts_in_initializer_lists
    - avoid_setters_without_getters
    - no_duplicate_case_values
    - prefer_generic_function_type_aliases
    - unnecessary_new
    - prefer_const_constructors_in_immutables
    - avoid_equals_and_hash_code_on_mutable_classes
    - prefer_const_literals_to_create_immutables
    - avoid_relative_lib_imports
    - sort_unnamed_constructors_first
    - prefer_function_declarations_over_variables
    - avoid_shadowing_type_parameters
    - package_api_docs
    - type_annotate_public_apis
    - annotate_overrides
    - prefer_final_in_for_each
    
errors:
  invalid_annotation_target: ignore